### ISSUE TITLE
Any thought of updating this?

### ISSUE THREAD

**Issue by zellyn** [nsf/golemon#3]
Hi there,

I ran across this while attempting to port [pikchr](https://pikchr.org/) to Go. Clearly, it's 11 years out of date, and not maintained. 🙂

I was _hoping_ that the original `lemon` would be stable enough that there would be, oh, six or seven or a dozen changes in the past 11 years, and I could just apply their equivalents. Unfortunately, there are a [lot more than that](https://sqlite.org/src/finfo?name=tool/lemon.c&m&ci=tip) 😞. (`pikchr.y` uses `%extra_context` in particular, but there are many important-looking changes besides that.)

Failing your lack of interest (which would be _entirely_ understandable!), I guess I could re-translate `lemon.c` — do you have any memory of how difficult/invasive it was, or how you went about it? Thanks, and sorry for the hassle!

**Comment by nsf** [comment]
Hello. Well, lemon is just a single .c file with a bunch of printf statements. It's quite messy. I took it and started converting all C declarations/statements to Go counterparts and that was it. IIRC lemon doesn't even use any fancy language constructs such as goto statements. It's all about tables, ifs and loops.

Easy to debug too, you can keep original lemon side by side and compare generated code of the modified Go version with C version. Given that you can read both C and Go, just hack the Go one until it looks right and works.

I would probably write pikchr parser by hand if I were you though. Looks relatively simple: https://pikchr.org/home/doc/trunk/doc/grammar.md

**Comment by zellyn** [comment]
Ok, that makes sense. I figured that was about what you'd done.

My motivation for using lemon and hand-porting `pikchr.y` to Go is that it would (a) automatically benefit from the sqlite folks' legendary code quality, and (b) it would make looking at future diffs in the upstream version and hand-applying them to mine easy too.

**Comment by zellyn** [comment]
As an irrelevant aside, it's kind of hilarious how far down the side-project yak-shaving stack I am right now! 😂

* Open my garage door and gate with a Raspberry Pi and radio transmitter
* Port the C code people have written for using DMA/SPI to Go
* Understand the C code people have written for DMA/SPI
* Write a couple of blog posts documenting how to do accurately-timed larger data bursts using DMA/SPI
* Draw diagrams in pikchr
* Get my hugo stack to support pikchr
* Get goldmark to support pikchr
* Port pikchr to pure Go
* Get the go port of the lemon parser working with `pikchr.y`
* Re-port golemon

At least I'm trying to leave the world better than I found it for future hackers! 😂

**Comment by zellyn** [comment]
FWIW, https://github.com/gopikchr/golemon is an updated port. It is hand-ported, but as mechanical as possible.
